local M = {}

---Build the full highlight table.
---@param c table palette colors (post on_colors)
---@param opts MonokaiCharcoalConfig
function M.get(c, opts)
  local s = opts.styles
  local bg = opts.transparent and c.none or c.bg
  local bg_dark = opts.transparent and c.none or c.bg_dark

  -- merge a base highlight with a style table ({ italic=true } etc.)
  local function st(base, style)
    return vim.tbl_extend("force", base, style or {})
  end

  local hl = {
    --------------------------------------------------------------------- editor
    Normal       = { fg = c.fg, bg = bg },
    NormalNC     = { fg = c.fg, bg = opts.dim_inactive and c.bg_dark or bg },
    NormalFloat  = { fg = c.fg, bg = bg_dark },
    FloatBorder  = { fg = c.border, bg = bg_dark },
    FloatTitle   = { fg = c.accent, bg = bg_dark, bold = true },
    ColorColumn  = { bg = c.bg_cursor },
    Conceal      = { fg = c.grey },
    Cursor       = { fg = c.bg, bg = c.fg },
    lCursor      = { fg = c.bg, bg = c.fg },
    CursorIM     = { fg = c.bg, bg = c.fg },
    CursorLine   = { bg = c.bg_cursor },
    CursorColumn = { bg = c.bg_cursor },
    CursorLineNr = { fg = c.accent, bold = true },
    LineNr       = { fg = c.accent },
    LineNrAbove  = { fg = c.grey },
    LineNrBelow  = { fg = c.grey },
    SignColumn   = { fg = c.grey, bg = bg },
    FoldColumn   = { fg = c.grey, bg = bg },
    Folded       = { fg = c.accent, bg = c.bg_dark },
    Directory    = { fg = c.cyan },
    EndOfBuffer  = { fg = bg == c.none and c.bg or bg },
    ErrorMsg     = { fg = c.red, bold = true },
    WarningMsg   = { fg = c.warn },
    ModeMsg      = { fg = c.fg, bold = true },
    MoreMsg      = { fg = c.cyan },
    MsgArea      = { fg = c.fg },
    MsgSeparator = { fg = c.border },
    NonText      = { fg = c.fg_gutter },
    Whitespace   = { fg = c.fg_gutter },
    SpecialKey   = { fg = c.fg_gutter },
    MatchParen   = { fg = c.orange, bold = true },
    Question     = { fg = c.cyan },
    Title        = { fg = c.green, bold = true },
    VertSplit    = { fg = c.border },
    WinSeparator = { fg = c.border },
    Visual       = { bg = c.bg_visual },
    VisualNOS    = { bg = c.bg_visual },
    Search       = { fg = c.bg, bg = c.yellow },
    IncSearch    = { fg = c.bg, bg = c.orange },
    CurSearch    = { fg = c.bg, bg = c.orange, bold = true },
    Substitute   = { fg = c.bg, bg = c.pink },
    Pmenu        = { fg = c.fg, bg = bg_dark },
    PmenuSel     = { fg = c.fg, bg = c.border, bold = true },
    PmenuSbar    = { bg = c.bg_dark },
    PmenuThumb   = { bg = c.accent },
    PmenuKind    = { fg = c.cyan, bg = bg_dark },
    PmenuExtra   = { fg = c.grey, bg = bg_dark },
    WildMenu     = { fg = c.bg, bg = c.accent },
    StatusLine   = { fg = c.accent, bg = bg_dark },
    StatusLineNC = { fg = c.grey, bg = bg_dark },
    TabLine      = { fg = c.grey, bg = bg_dark },
    TabLineFill  = { bg = bg },
    TabLineSel   = { fg = c.fg, bg = bg, bold = true },
    WinBar       = { fg = c.accent, bg = bg },
    WinBarNC     = { fg = c.grey, bg = bg },
    QuickFixLine = { bg = c.bg_cursor, bold = true },
    debugPC      = { bg = c.bg_dark },
    debugBreakpoint = { fg = c.red, bg = bg },

    --------------------------------------------------------------- spell / misc
    SpellBad     = { sp = c.red, undercurl = true },
    SpellCap     = { sp = c.warn, undercurl = true },
    SpellLocal   = { sp = c.cyan, undercurl = true },
    SpellRare    = { sp = c.purple, undercurl = true },

    ------------------------------------------------------- classic syntax groups
    Comment        = st({ fg = c.orange }, s.comments),
    Constant       = { fg = c.purple },
    String         = st({ fg = c.yellow }, s.strings),
    Character      = { fg = c.purple },
    Number         = { fg = c.purple },
    Float          = { fg = c.purple },
    Boolean        = st({ fg = c.purple }, s.booleans),
    Identifier     = st({ fg = c.fg }, s.variables),
    Function       = st({ fg = c.green }, s.functions),
    Statement      = st({ fg = c.pink }, s.keywords),
    Conditional    = st({ fg = c.pink }, s.keywords),
    Repeat         = st({ fg = c.pink }, s.keywords),
    Label          = { fg = c.pink },
    Operator       = { fg = c.pink },
    Keyword        = st({ fg = c.pink }, s.keywords),
    Exception      = st({ fg = c.pink }, s.keywords),
    PreProc        = { fg = c.pink },
    Include        = { fg = c.pink },
    Define         = { fg = c.pink },
    Macro          = { fg = c.cyan },
    PreCondit      = { fg = c.pink },
    Type           = st({ fg = c.cyan }, s.types),
    StorageClass   = st({ fg = c.cyan }, s.types),
    Structure      = st({ fg = c.cyan }, s.types),
    Typedef        = st({ fg = c.cyan }, s.types),
    Special        = { fg = c.orange },
    SpecialChar    = { fg = c.purple },
    Tag            = { fg = c.pink, bold = true },
    Delimiter      = { fg = c.fg },
    SpecialComment = { fg = c.grey, bold = true },
    Debug          = { fg = c.orange },
    Underlined     = { underline = true },
    Bold           = { bold = true },
    Italic         = { italic = true },
    Ignore         = { fg = c.grey },
    Error          = { fg = c.fg, bg = c.pink },
    Todo           = { fg = c.bg, bg = c.yellow, bold = true },

    ----------------------------------------------------------------- diagnostics
    DiagnosticError = { fg = c.red },
    DiagnosticWarn  = { fg = c.warn },
    DiagnosticInfo  = { fg = c.info },
    DiagnosticHint  = { fg = c.hint },
    DiagnosticOk    = { fg = c.ok },
    DiagnosticVirtualTextError = { fg = c.red, bg = bg },
    DiagnosticVirtualTextWarn  = { fg = c.warn, bg = bg },
    DiagnosticVirtualTextInfo  = { fg = c.info, bg = bg },
    DiagnosticVirtualTextHint  = { fg = c.hint, bg = bg },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn  = { sp = c.warn, undercurl = true },
    DiagnosticUnderlineInfo  = { sp = c.info, undercurl = true },
    DiagnosticUnderlineHint  = { sp = c.hint, undercurl = true },
    DiagnosticUnnecessary    = { fg = c.grey },
    DiagnosticDeprecated     = { fg = c.grey, strikethrough = true },

    ------------------------------------------------------------------- lsp / ref
    LspReferenceText  = { bg = c.bg_cursor },
    LspReferenceRead  = { bg = c.bg_cursor },
    LspReferenceWrite = { bg = c.bg_cursor },
    LspSignatureActiveParameter = { fg = c.orange, bold = true },
    LspInlayHint = { fg = c.grey, bg = c.bg_dark },
    LspCodeLens  = { fg = c.grey },

    ------------------------------------------------------------------ treesitter
    ["@comment"]              = st({ fg = c.orange }, s.comments),
    ["@comment.documentation"] = { fg = c.grey },
    ["@comment.error"]        = { fg = c.bg, bg = c.red },
    ["@comment.warning"]      = { fg = c.bg, bg = c.warn },
    ["@comment.todo"]         = { fg = c.bg, bg = c.yellow, bold = true },
    ["@comment.note"]         = { fg = c.bg, bg = c.info },
    ["@error"]                = { fg = c.red },
    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.bracket"]  = { fg = c.fg },
    ["@punctuation.special"]  = { fg = c.purple },
    ["@constant"]             = { fg = c.purple },
    ["@constant.builtin"]     = { fg = c.purple },
    ["@constant.macro"]       = { fg = c.cyan },
    ["@string"]               = st({ fg = c.yellow }, s.strings),
    ["@string.regexp"]        = { fg = c.orange },
    ["@string.escape"]        = { fg = c.purple },
    ["@string.special"]       = { fg = c.purple },
    ["@string.special.url"]   = { fg = c.cyan, underline = true },
    ["@character"]            = { fg = c.purple },
    ["@character.special"]    = { fg = c.purple },
    ["@number"]               = { fg = c.purple },
    ["@number.float"]         = { fg = c.purple },
    ["@boolean"]              = st({ fg = c.purple }, s.booleans),
    ["@float"]                = { fg = c.purple },
    ["@function"]             = st({ fg = c.green }, s.functions),
    ["@function.builtin"]     = { fg = c.cyan },
    ["@function.call"]        = st({ fg = c.green }, s.functions),
    ["@function.macro"]       = { fg = c.cyan },
    ["@function.method"]      = st({ fg = c.green }, s.functions),
    ["@function.method.call"] = st({ fg = c.green }, s.functions),
    ["@constructor"]          = { fg = c.cyan },
    ["@parameter"]            = { fg = c.orange, italic = true },
    ["@variable.parameter"]   = { fg = c.orange, italic = true },
    ["@keyword"]              = st({ fg = c.pink }, s.keywords),
    ["@keyword.function"]     = st({ fg = c.pink }, s.keywords),
    ["@keyword.operator"]     = { fg = c.pink },
    ["@keyword.return"]       = st({ fg = c.pink }, s.keywords),
    ["@keyword.import"]       = { fg = c.pink },
    ["@keyword.exception"]    = st({ fg = c.pink }, s.keywords),
    ["@keyword.conditional"]  = st({ fg = c.pink }, s.keywords),
    ["@keyword.repeat"]       = st({ fg = c.pink }, s.keywords),
    ["@keyword.coroutine"]    = { fg = c.pink },
    ["@conditional"]          = st({ fg = c.pink }, s.keywords),
    ["@repeat"]               = st({ fg = c.pink }, s.keywords),
    ["@label"]                = { fg = c.pink },
    ["@operator"]             = { fg = c.pink },
    ["@exception"]            = st({ fg = c.pink }, s.keywords),
    ["@type"]                 = st({ fg = c.cyan }, s.types),
    ["@type.builtin"]         = st({ fg = c.cyan }, s.types),
    ["@type.definition"]      = st({ fg = c.cyan }, s.types),
    ["@type.qualifier"]       = { fg = c.pink },
    ["@storageclass"]         = { fg = c.pink },
    ["@attribute"]            = { fg = c.green },
    ["@property"]             = { fg = c.fg },
    ["@field"]                = { fg = c.fg },
    ["@variable"]             = st({ fg = c.fg }, s.variables),
    ["@variable.builtin"]     = { fg = c.green },
    ["@variable.member"]      = { fg = c.fg },
    ["@namespace"]            = { fg = c.cyan, italic = true },
    ["@module"]               = { fg = c.cyan, italic = true },
    ["@module.builtin"]       = { fg = c.cyan },
    ["@symbol"]               = { fg = c.purple },
    ["@text"]                 = { fg = c.fg },
    ["@text.strong"]          = { bold = true },
    ["@text.emphasis"]        = { italic = true },
    ["@text.underline"]       = { underline = true },
    ["@text.strike"]          = { strikethrough = true },
    ["@text.title"]           = { fg = c.green, bold = true },
    ["@text.literal"]         = { fg = c.cyan },
    ["@text.uri"]             = { fg = c.cyan, underline = true },
    ["@text.reference"]       = { fg = c.cyan },
    ["@text.todo"]            = { fg = c.bg, bg = c.yellow, bold = true },
    ["@text.note"]            = { fg = c.bg, bg = c.info, bold = true },
    ["@text.warning"]         = { fg = c.bg, bg = c.warn, bold = true },
    ["@text.danger"]          = { fg = c.bg, bg = c.red, bold = true },
    ["@text.diff.add"]        = { fg = c.git_add },
    ["@text.diff.delete"]     = { fg = c.git_delete },
    ["@tag"]                  = { fg = c.pink, bold = true },
    ["@tag.attribute"]        = { fg = c.green },
    ["@tag.delimiter"]        = { fg = c.fg },

    -- nvim 0.10+ markup captures
    ["@markup.heading"]       = { fg = c.green, bold = true },
    ["@markup.heading.1"]     = { fg = c.green, bold = true },
    ["@markup.heading.2"]     = { fg = c.cyan, bold = true },
    ["@markup.heading.3"]     = { fg = c.yellow, bold = true },
    ["@markup.heading.4"]     = { fg = c.pink, bold = true },
    ["@markup.strong"]        = { fg = c.fg, bold = true },
    ["@markup.italic"]        = { fg = c.fg, italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"]     = { underline = true },
    ["@markup.raw"]           = { fg = c.cyan },
    ["@markup.raw.block"]     = { fg = c.cyan },
    ["@markup.link"]          = { fg = c.cyan },
    ["@markup.link.label"]    = { fg = c.pink },
    ["@markup.link.url"]      = { fg = c.cyan, underline = true },
    ["@markup.list"]          = { fg = c.purple },
    ["@markup.list.checked"]  = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.grey },
    ["@markup.quote"]         = { fg = c.grey, italic = true },
    ["@markup.math"]          = { fg = c.purple },

    ---------------------------------------------------------- lsp semantic tokens
    ["@lsp.type.class"]         = st({ fg = c.cyan }, s.types),
    ["@lsp.type.comment"]       = {},
    ["@lsp.type.decorator"]     = { fg = c.green },
    ["@lsp.type.enum"]          = st({ fg = c.cyan }, s.types),
    ["@lsp.type.enumMember"]    = { fg = c.purple },
    ["@lsp.type.function"]      = st({ fg = c.green }, s.functions),
    ["@lsp.type.interface"]     = st({ fg = c.cyan }, s.types),
    ["@lsp.type.macro"]         = { fg = c.cyan },
    ["@lsp.type.method"]        = st({ fg = c.green }, s.functions),
    ["@lsp.type.namespace"]     = { fg = c.cyan, italic = true },
    ["@lsp.type.parameter"]     = { fg = c.orange, italic = true },
    ["@lsp.type.property"]       = { fg = c.fg },
    ["@lsp.type.struct"]        = st({ fg = c.cyan }, s.types),
    ["@lsp.type.type"]          = st({ fg = c.cyan }, s.types),
    ["@lsp.type.typeParameter"] = st({ fg = c.cyan }, s.types),
    ["@lsp.type.variable"]      = st({ fg = c.fg }, s.variables),
    ["@lsp.typemod.variable.readonly"] = { fg = c.purple },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = c.green },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = c.cyan },

    --------------------------------------------------------------- diff / git core
    DiffAdd      = { fg = c.git_add, bg = bg },
    DiffChange   = { fg = c.git_change, bg = bg },
    DiffDelete   = { fg = c.git_delete, bg = bg },
    DiffText     = { fg = c.fg, bg = c.border_dim },
    diffAdded    = { fg = c.git_add },
    diffRemoved  = { fg = c.git_delete },
    diffChanged  = { fg = c.git_change },
    diffOldFile  = { fg = c.grey },
    diffNewFile  = { fg = c.fg },
    diffFile     = { fg = c.cyan },
    diffLine     = { fg = c.purple },
    diffIndexLine = { fg = c.cyan },

    ----------------------------------------------------------------- plugin: gitsigns
    GitSignsAdd    = { fg = c.git_add, bg = bg },
    GitSignsChange = { fg = c.git_change, bg = bg },
    GitSignsDelete = { fg = c.git_delete, bg = bg },
    GitSignsCurrentLineBlame = { fg = c.grey },

    --------------------------------------------------------------- plugin: telescope
    TelescopeNormal       = { fg = c.fg, bg = bg_dark },
    TelescopeBorder       = { fg = c.border, bg = bg_dark },
    TelescopeTitle        = { fg = c.accent, bold = true },
    TelescopePromptNormal = { fg = c.fg, bg = c.bg_dark },
    TelescopePromptBorder = { fg = c.border, bg = c.bg_dark },
    TelescopePromptTitle  = { fg = c.bg, bg = c.accent, bold = true },
    TelescopePromptPrefix = { fg = c.pink },
    TelescopeResultsTitle = { fg = c.accent },
    TelescopePreviewTitle = { fg = c.green },
    TelescopeSelection    = { fg = c.fg, bg = c.border, bold = true },
    TelescopeSelectionCaret = { fg = c.pink },
    TelescopeMatching     = { fg = c.orange, bold = true },

    ------------------------------------------------------------- plugin: nvim-cmp
    CmpItemAbbr            = { fg = c.fg },
    CmpItemAbbrDeprecated  = { fg = c.grey, strikethrough = true },
    CmpItemAbbrMatch       = { fg = c.orange, bold = true },
    CmpItemAbbrMatchFuzzy  = { fg = c.orange, bold = true },
    CmpItemMenu            = { fg = c.grey },
    CmpItemKindText        = { fg = c.fg },
    CmpItemKindMethod      = { fg = c.green },
    CmpItemKindFunction    = { fg = c.green },
    CmpItemKindConstructor = { fg = c.cyan },
    CmpItemKindField       = { fg = c.fg },
    CmpItemKindVariable    = { fg = c.fg },
    CmpItemKindClass       = { fg = c.cyan },
    CmpItemKindInterface   = { fg = c.cyan },
    CmpItemKindModule      = { fg = c.cyan },
    CmpItemKindProperty    = { fg = c.fg },
    CmpItemKindKeyword     = { fg = c.pink },
    CmpItemKindSnippet     = { fg = c.yellow },
    CmpItemKindColor       = { fg = c.purple },
    CmpItemKindConstant    = { fg = c.purple },
    CmpItemKindEnum        = { fg = c.cyan },
    CmpItemKindValue       = { fg = c.purple },

    -------------------------------------------------------------- plugin: blink.cmp
    BlinkCmpMenuBorder      = { fg = c.border, bg = bg_dark },
    BlinkCmpLabelMatch      = { fg = c.orange, bold = true },
    BlinkCmpLabelDeprecated = { fg = c.grey, strikethrough = true },
    BlinkCmpKind            = { fg = c.cyan },

    ----------------------------------------------------- plugin: nvim-tree / neo-tree
    NvimTreeNormal       = { fg = c.fg, bg = bg_dark },
    NvimTreeRootFolder   = { fg = c.accent, bold = true },
    NvimTreeFolderName   = { fg = c.cyan },
    NvimTreeFolderIcon   = { fg = c.accent },
    NvimTreeOpenedFolderName = { fg = c.cyan, bold = true },
    NvimTreeSpecialFile  = { fg = c.green },
    NvimTreeGitDirty     = { fg = c.git_change },
    NvimTreeGitNew       = { fg = c.git_add },
    NvimTreeGitDeleted   = { fg = c.git_delete },
    NvimTreeIndentMarker = { fg = c.border_dim },
    NvimTreeWinSeparator = { fg = c.border, bg = bg },

    NeoTreeNormal        = { fg = c.fg, bg = bg_dark },
    NeoTreeNormalNC      = { fg = c.fg, bg = bg_dark },
    NeoTreeDirectoryName = { fg = c.cyan },
    NeoTreeDirectoryIcon = { fg = c.accent },
    NeoTreeRootName      = { fg = c.accent, bold = true },
    NeoTreeGitAdded      = { fg = c.git_add },
    NeoTreeGitModified   = { fg = c.git_change },
    NeoTreeGitDeleted    = { fg = c.git_delete },
    NeoTreeIndentMarker  = { fg = c.border_dim },

    -------------------------------------------------------------- plugin: bufferline
    BufferLineFill            = { bg = bg },
    BufferLineBackground      = { fg = c.grey, bg = bg_dark },
    BufferLineBufferSelected  = { fg = c.fg, bg = bg, bold = true },
    BufferLineBufferVisible   = { fg = c.grey, bg = bg_dark },
    BufferLineIndicatorSelected = { fg = c.accent },
    BufferLineModified        = { fg = c.git_change },
    BufferLineModifiedSelected = { fg = c.git_change },

    -------------------------------------------- plugin: indent-blankline (ibl v3)
    IblIndent    = { fg = c.fg_gutter },
    IblScope     = { fg = c.border },
    IblWhitespace = { fg = c.fg_gutter },

    --------------------------------------------------------------- plugin: which-key
    WhichKey          = { fg = c.pink },
    WhichKeyGroup     = { fg = c.cyan },
    WhichKeyDesc      = { fg = c.fg },
    WhichKeySeparator = { fg = c.grey },
    WhichKeyFloat     = { bg = bg_dark },
    WhichKeyBorder    = { fg = c.border, bg = bg_dark },

    --------------------------------------------------------------- plugin: notify
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder  = { fg = c.warn },
    NotifyINFOBorder  = { fg = c.info },
    NotifyDEBUGBorder = { fg = c.grey },
    NotifyTRACEBorder = { fg = c.purple },
    NotifyERRORIcon   = { fg = c.red },
    NotifyWARNIcon    = { fg = c.warn },
    NotifyINFOIcon    = { fg = c.info },
    NotifyERRORTitle  = { fg = c.red },
    NotifyWARNTitle   = { fg = c.warn },
    NotifyINFOTitle   = { fg = c.info },

    ------------------------------------------------------------------ plugin: dap
    DapUIScope       = { fg = c.cyan },
    DapUIType        = { fg = c.purple },
    DapUIValue       = { fg = c.fg },
    DapUIVariable    = { fg = c.fg },
    DapUIBreakpointsPath = { fg = c.cyan },
    DapUIBreakpointsInfo = { fg = c.green },
    DapUILineNumber  = { fg = c.accent },
    DapUIStoppedThread = { fg = c.accent },

    ------------------------------------------------------------ plugin: mini.* / misc
    MiniStatuslineModeNormal  = { fg = c.bg, bg = c.accent, bold = true },
    MiniStatuslineModeInsert  = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeVisual  = { fg = c.bg, bg = c.pink, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.orange, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
    MiniIndentscopeSymbol     = { fg = c.border },
    RainbowDelimiterRed    = { fg = c.pink },
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterBlue   = { fg = c.cyan },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterGreen  = { fg = c.green },
    RainbowDelimiterViolet = { fg = c.purple },
    RainbowDelimiterCyan   = { fg = c.accent },

    --------------------------------------------------------- markdown (builtin ft)
    markdownHeadingDelimiter = { fg = c.green },
    markdownH1   = { fg = c.green, bold = true },
    markdownH2   = { fg = c.cyan, bold = true },
    markdownH3   = { fg = c.yellow, bold = true },
    markdownCode = { fg = c.cyan },
    markdownCodeBlock = { fg = c.cyan },
    markdownLink = { fg = c.cyan, underline = true },
    markdownUrl  = { fg = c.cyan, underline = true },
    markdownListMarker = { fg = c.purple },
    markdownBold = { fg = c.fg, bold = true },
    markdownItalic = { fg = c.fg, italic = true },

    --------------------------------------------------------------------- help ft
    helpHyperTextEntry = { fg = c.green },
    helpHyperTextJump  = { fg = c.cyan, underline = true },
    helpExample        = { fg = c.yellow },
    helpCommand        = { fg = c.cyan },
  }

  return hl
end

return M
